<?php // generated by https://www.devsense.com/

/**
 * Sets the client character set
 *
 * @param mysqli $mysql A link identifier returned by mysqli_connect() or mysqli_init()
 * @param string $charset The desired character set.
 * @return bool Returns `true` on success or `false` on failure.
 */
function mysqli_set_charset(mysqli $mysql, string $charset): bool
{ /* function body is hidden */
}